---
title: Fig Balsamic Dressing
author: Fresh Corner Market
date: '2024-08-09'
slug: fig-balsamic-dressing
categories:
  - Recipes
tags:
  - Recipes
  - Dressing
  - Vegan
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

by Fresh Corner Market (University of Oregon)

# Ingredients

```{r}
library(tidyverse)
library(kableExtra)

ingredients <- 
  tribble(
    ~Ingredient, ~Amount,
    'Soaked Black Mission Figs', '10',
    'Balsamic Vinegar', "1/3 Cup",
    'Olive Oil', '1 Cup',
    'Black Pepper', '1/2 tsp',
    'Salt', '1 tsp',
    'Lemon Juice', '1 tsp',
    'Dijon Mustard', '1 Tbsp'
  )

knitr::kable(ingredients, align = 'lr') |> 
  kable_styling(full_width = T) |>
  add_header_above(c("Yields 2 Cups" = 2))

```


# Preparation 

0. Pre-soak Black Mission Figs in 1 cup of water for 2 hours, then reserve the water for later. 

1. Blend all ingredients until smooth, starting slow and adding reserved water if necessary.
2. Should be creamy and thick. 